Develop
TUW-GEO/colorella pull request #3
Opened 2020-06-03 10:59 UTC by FelixReuss

2020-06-03 15:02 UTC, sebhahn requested changes
Please run a pep8 check of the code (using e.g. autopep8)

2020-06-03 15:02 UTC, sebhahn commented on src/colorella/colormap.py
> +    def __init__(self, arg, cm_dirpath='./colormaps', name=None):
the path is not independent for the user OS

2020-06-03 15:02 UTC, sebhahn commented on src/colorella/colormap.py
> +        Saves a acolormap.object as a gdal .ct file
typo

2020-06-03 15:02 UTC, sebhahn commented on src/colorella/colormap.py
> +            for i in range(len(self._mpl_cm.colors)):
can this be done without a loop? `self._mpl_cm.colors` is it an array or list?

2020-06-03 15:02 UTC, sebhahn commented on src/colorella/colormap.py
> +            raise Exception('')
Exception is too general and please add a message

2020-06-03 15:02 UTC, sebhahn commented
The tests are also not working

2020-06-03 15:06 UTC, sebhahn commented
I also talked to @cnavacch, it would be good to make the dependency of `gdal` optional, i.e. gdal functions can only be used if the package has been installed before, but is not installed by default

2020-06-03 15:12 UTC, cnavacch commented
@sebhahn : Thanks for the reviews, but we should have informed you that this is only a preliminary PR. Felix and I did not had the chance to speak to each other to apply the changes we have discussed the last time. Felix will let you know as soon as the changes are deployed.

2020-06-03 15:31 UTC, sebhahn commented
Ok, but the tests should be working for this PR.

2020-06-10 06:41 UTC, cnavacch commented on README.md
> +
Needs further descriptions, please have a look at other packages.

2020-06-10 07:28 UTC, cnavacch requested changes
Please fix my comments before merging. I have three additional comments, which I was not able to mark in the PR:

1. What is "src/colorella/colormaps/etopo1.cpt " doing under colormaps? There should only be ct files.
2. Some functions still do not have a proper NumPy Style documentation, please fix this.
3. Sometimes you use a `try` and `except` block to read a file. I would prefer to use `os.path.exists()`.
4. Have you setup ReadTheDocs already? I would also do this before merging. 
5. Sometimes you have a camel-case variable naming. Please use lower letters with underscores to follow the PEP-8 convention.

2020-06-10 07:28 UTC, cnavacch commented on src/colorella/colormap.py
> +    raise warnings.warn(gdal_warning)
I would only raise the warning when the user tries to execute one of the functions

2020-06-10 07:28 UTC, cnavacch commented on src/colorella/colormap.py
> +            return cls.from_dict(colors, name=name)
You do not need to check a truth value, use:
```
        if gradient:
             return cls.from_dict(colors, name=name)
        else:
             return cls.from_list(colors, name=name, gradient=gradient)
```

2020-06-10 07:28 UTC, cnavacch commented on src/colorella/colormap.py
> +        mpl_cm = col.LinearSegmentedColormap.from_list(self._mpl_cm.name +'_grey', colors, self._mpl_cm.N)
You can call `self.name` instead of `self._mpl_cm.name`

2020-06-10 07:28 UTC, cnavacch commented on src/colorella/colormap.py
> +            mpl_cm = mpl.colors.LinearSegmentedColormap(segmentdata=revdict, name=self._mpl_cm.name + '_reversed')
You can call `self.name` instead of `self._mpl_cm.name`

2020-06-10 07:28 UTC, cnavacch commented on src/colorella/colormap.py
> +            mpl_cm = col.LinearSegmentedColormap.from_list(name=self._mpl_cm.name+'_gradient', colors=self._mpl_cm.colors)
You can call `self.name` instead of `self._mpl_cm.name`

2020-06-10 07:28 UTC, cnavacch commented on src/colorella/colormap.py
> +gdal_warning = 'No GDAL Installation found. Without gdal the following functions are not available: from_gdal, to_gdal'
Fine to define it here, but write it in capital letters. This makes it clear, that it is a global variable

2020-06-10 07:28 UTC, cnavacch commented on src/colorella/colormap.py
> +                    gdal_ct.SetColorEntry(i, tuple((255, 255, 255)) + (0,))
Maybe you move this part to the conversion.py file?

2020-06-14 21:06 UTC, cnavacch requested changes

2020-06-14 21:06 UTC, cnavacch commented on tests/test_colormap.py
> +    raise warnings.warn(gdal_warning)
This should only be raised when a gdal function is explicitly called. It is enough when you define it in the colormap class and catch the warning in the test class.

2020-06-15 09:12 UTC, cnavacch requested changes

2020-06-15 09:12 UTC, cnavacch commented on src/colorella/colormap.py
> +            if gradient == False:
Again, you evaluate a boolean to `== true` or `== false`. Use if `gradient` or `if not gradient.`

2020-06-15 09:12 UTC, cnavacch commented on README.md
> +<!DOCTYPE html>
This should not be here as an html file. if you want to integrate the graphic use png or jpeg, not plain SVG.

2020-06-15 09:12 UTC, cnavacch commented on docs/index_old.rst
> +=========
please use one index file, not two.

2020-06-15 09:12 UTC, cnavacch commented on src/colorella/conversions.py
> +        return None
not really necessary when error is thrown before

2020-06-15 09:12 UTC, cnavacch commented on src/colorella/conversions.py
> +                        continue
You could shorten this by saying:
```                    
 if ls[-1] == "HSV":
     color_model = "HSV"
 continue
```

2020-06-15 09:12 UTC, cnavacch commented on src/colorella/colormap.py
> +            raise ValueError('File extensions is not recognized, supported file extensions are: .cpt, .ct, .json')
You could shorten this by putting the inner gradient if clause outside and after the outer if clause.

2020-06-15 09:12 UTC, cnavacch commented on src/colorella/colormap.py
> +            return cls.from_dict(cpt_dict, name=name)
again, do the boolean check without `==`

2020-06-15 11:32 UTC, cnavacch requested changes

2020-06-15 11:32 UTC, cnavacch commented on src/colorella/colormap.py
> +    warnings.warn(gdal_warning)
I would only print a warning in the GDAL functions.

2020-06-15 11:32 UTC, cnavacch commented on src/colorella/conversions.py
> -        return None
Could you please remove this also for the other file processes where an ImportError is raised?

2020-06-15 12:00 UTC, cnavacch approved these changes

2020-06-15 12:02 UTC, cnavacch commented
@sebhahn Could you please take another look at the code and give some final feedback? Felix can then finally complete the PR after he resolved your comments :-)

2020-06-15 12:31 UTC, sebhahn requested changes
Some minor comments

2020-06-15 12:31 UTC, sebhahn commented on docs/conf.py
> +sys.path.insert(0, os.path.abspath('H:\GIT\colorella'))
Why is this path in here and hardcoded?

2020-06-15 12:31 UTC, sebhahn commented on docs/conf.py
> +author = 'Felix Reuss'
We usually use 'TU Wien' as author and copyright

2020-06-15 12:31 UTC, sebhahn commented on src/colorella/conversions.py
> +        raise ImportError("file ", filepath, "not found")
I would recommend

```
if not os.path.exists(filepath):
    raise ImportError("file ", filepath, "not found")

# no else
file = open(filepath)
name = os.path.splitext(os.path.basename(filepath))[0]
lines = file.readlines()
file.close()
...
return ...
```

2020-06-15 12:31 UTC, sebhahn commented on src/colorella/conversions.py
> +    else:
see comment above

2020-06-15 12:31 UTC, sebhahn commented on src/colorella/conversions.py
> +    else:
see comment above

2020-06-15 14:07 UTC, merged